chore(backend): Only compiling the preloaded samples. Fixes #4117 (#4118)
* Backend - Only compiling the preloaded samples

Fixes https://github.com/kubeflow/pipelines/issues/4117

* Fixed the paths

* Removed -o pipefail for now since sh does not support it

* Fixed the quotes

* Removed the __future__ imports

Python 2 is no longer supported.
The annotations cause compilation problems:
```
  File "/samples/core/iris/iris.py", line 18
    from __future__ import absolute_import
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```