Removed the __future__ imports
Python 2 is no longer supported.
The annotations cause compilation problems:
```
  File "/samples/core/iris/iris.py", line 18
    from __future__ import absolute_import
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```