TFT: Do not reuse training metadata for writing eval data. (#567)
This change modifies the TFT component such that the schema
used for writing post-training eval data comes from the generation
of the eval data rather than from the generation of the training data.

Conceptually, the schema from both steps should be identical, but
reusing the metadata from preprocessing the training set causes issues
if the type of the target field is different after preprocessing.

For example, when training on the Chicago Public Taxi dataset, if the
preprocessing function converts the type of the `tips` field from a
number to a boolean, then writing the preprocessed eval data will fail
with an error message saying:

```
AttributeError: 'numpy.bool_' object has no attribute 'encode'
```

By using the schema from the preprocessing of the eval data to write
that data, this error goes away.