SDK/DSL: Fix bug when using PipelineParam in `pvc` of PipelineVolume
If no `name` is provided to PipelineVolume constructor, a custom name is
generated. It relies on `json.dumps()` of the struct after getting
converted to dict.
When `pvc` is provided and `name` is not, the following error is raised:
  TypeError: Object of type PipelineParam is not JSON serializable

This commit fixes it and extends tests to catch it.